Add support for alternative interface names
redhat-plumbers/systemd-rhel8 pull request #200
Opened 2021-07-22 17:48 UTC by dtardon

2021-08-30 09:29 UTC, msekletar approved these changes
LGTM (minor nitpick regarding indentation, but that is not important enough to warrant respin).

2021-08-30 09:29 UTC, msekletar commented on src/network/networkd-network-gperf.gperf
> +Match.Name,                             config_parse_match_ifnames,                           0,                             offsetof(Network, match_name)
nitpick, indentation is off.

2021-09-14 16:21 UTC, mrc0mmand requested changes
@dtardon please backport https://github.com/systemd/systemd/pull/16501 as well, otherwise assigning altnames might (and does) fail with -EEXIST.

2021-09-17 12:26 UTC, dtardon commented
> @dtardon please backport [systemd/systemd#16501](https://github.com/systemd/systemd/pull/16501) as well, otherwise assigning altnames might (and does) fail with -EEXIST.

Done.

2021-09-17 12:41 UTC, mrc0mmand commented
This looks relevant:

```
[2021-09-17 12:30:28] [build-stdout] ../src/network/netdev/netdev.c: In function ‘netdev_load_one’:
[2021-09-17 12:30:28] [build-stdout] ../src/network/netdev/netdev.c:639:13: error: too few arguments to function ‘net_match_config’
[2021-09-17 12:30:28] [build-stdout]   639 |         if (net_match_config(NULL, NULL, NULL, NULL, NULL,
[2021-09-17 12:30:28] [build-stdout]       |             ^~~~~~~~~~~~~~~~
[2021-09-17 12:30:28] [build-stdout] In file included from ../src/network/netdev/netdev.c:11:
[2021-09-17 12:30:28] [build-stdout] ../src/libsystemd-network/network-internal.h:17:6: note: declared here
[2021-09-17 12:30:28] [build-stdout]    17 | bool net_match_config(Set *match_mac,
[2021-09-17 12:30:28] [build-stdout]       |      ^~~~~~~~~~~~~~~~
```

2021-09-17 12:47 UTC, dtardon commented
> This looks relevant:
> 
> ```
> [2021-09-17 12:30:28] [build-stdout] ../src/network/netdev/netdev.c: In function ‘netdev_load_one’:
> [2021-09-17 12:30:28] [build-stdout] ../src/network/netdev/netdev.c:639:13: error: too few arguments to function ‘net_match_config’
> ```

That file shouldn't even be built, should it? It's part of networkd.

2021-09-17 12:48 UTC, mrc0mmand commented
> > This looks relevant:
> > ```
> > [2021-09-17 12:30:28] [build-stdout] ../src/network/netdev/netdev.c: In function ‘netdev_load_one’:
> > [2021-09-17 12:30:28] [build-stdout] ../src/network/netdev/netdev.c:639:13: error: too few arguments to function ‘net_match_config’
> > ```
> 
> That file shouldn't even be built, should it? It's part of networkd.

LGTM doesn't use the RHEL feature switches, so it builds the "default" configuration.

2021-09-17 12:52 UTC, dtardon commented
> LGTM doesn't use the RHEL feature switches, so it builds the "default" configuration.

Well, I intentionally dropped most changes in `src/network` because of too many merge conflicts. I didn't--and still don't--want to spend hours or even days fixing build of something we don't even use...

2021-09-17 12:52 UTC, mrc0mmand commented
> > LGTM doesn't use the RHEL feature switches, so it builds the "default" configuration.
> 
> Well, I intentionally dropped most changes in `src/network` because of too many merge conflicts. I didn't--and still don't--want to spend hours or even days fixing build of something we don't even use...

Lemme see if I can tweak the LGTM config.

2021-09-17 12:56 UTC, mrc0mmand commented
@dtardon could you add a simple RHEL-only patch, which disables networkd by default? I.e.:

```patch
diff --git a/meson_options.txt b/meson_options.txt
index 213079ac15..62a1302f54 100644
--- a/meson_options.txt
+++ b/meson_options.txt
@@ -86,7 +86,7 @@ option('machined', type : 'boolean',
        description : 'install the systemd-machined stack')
 option('portabled', type : 'boolean',
        description : 'install the systemd-portabled stack')
-option('networkd', type : 'boolean',
+option('networkd', type : 'boolean', value : false,
        description : 'install the systemd-networkd stack')
 option('timedated', type : 'boolean',
        description : 'install the systemd-timedated daemon')
```

that should be imo the easiest option here.

2021-09-17 13:05 UTC, merged

2021-09-17 13:56 UTC, dtardon commented
LGTM fix continued in #211.