(#2018024) rpm: Fix typo in %_environmentdir
redhat-plumbers/systemd-rhel8 pull request #228
Opened 2021-10-28 02:49 UTC by carlwgeorge

This is a backport of upstream commits to fix the misspelled %_environmentdir macro.

2021-10-28 02:53 UTC, Conan-Kudo approved these changes

2021-10-28 14:56 UTC, jamacku requested changes
@carlwgeorge Thanks for PR! 

Could you please set as target branch ``master`` instead of ``rhel-8.6.0``.
Also, could you please clone bugzilla to RHEL 8.
And then please add line ``Resolves: #<RHEL8-bugzilla>`` at the end of each commit message.

2021-10-29 21:11 UTC, carlwgeorge commented
[rhbz#2018024](https://bugzilla.redhat.com/show_bug.cgi?id=2018024) is a RHEL 8 bugzilla.  I've amended each of the commits with the necessary Resolves/Related messages.

2021-11-01 09:30 UTC, dtardon approved these changes
LGTM

2021-11-01 12:13 UTC, jamacku approved these changes

2021-11-01 12:20 UTC, merged