Support defining mount units on the kernel command line
redhat-plumbers/systemd-rhel8 pull request #398
Opened 2023-06-20 15:00 UTC by dtardon

Resolves: [#2190228](https://bugzilla.redhat.com/show_bug.cgi?id=2190228)

2023-07-12 12:49 UTC, msekletar requested changes

2023-07-12 12:49 UTC, msekletar commented on src/fstab-generator/fstab-generator.c
> +        r = add_mounts_from_cmdline();
I think the error handling is incorrect here. Main error code returned by generator depends on value of `r`. Previously, generator would return error return code when `fstab` processing failed. Now, (w/o any units on the command line which is the default case) this potential error would be obscured by `0` returned from `add_mounts_from_cmdline()` where there are no mounts on the command line.

2023-07-19 06:33 UTC, dtardon commented on src/fstab-generator/fstab-generator.c
> +                if (r < 0 && ret >= 0)
True, but it's harmless.

2024-01-18 08:58 UTC, jamacku commented
@dtardon Could you please have a look at the conflict in `fstab-generator.c`. Thank you

Also please reference the [RHEL-5989](https://issues.redhat.com/browse/RHEL-5989) instead of [#2190228](https://bugzilla.redhat.com/show_bug.cgi?id=2190228)

2024-01-18 09:07 UTC, jamacku requested changes
Related upstream follow-ups:
- https://github.com/systemd/systemd/pull/28518
- https://github.com/systemd/systemd/pull/28544

We should include them as well.

2024-02-05 08:15 UTC, jamacku commented
It's too late for RHEL 8, hence closing this PR.

2024-02-05 08:15 UTC, closed without merging